services:
  reaction:
    image: ghcr.io/uilpx/reaction:${IMAGE_TAG:-latest}
    pull_policy: always
    container_name: reaction
    restart: unless-stopped
    volumes:
      - ${REACTION_DB_PATH:-./data/data.db}:/app/data/data.db
    networks:
      webnet:
        aliases:
          - reaction

networks:
  webnet:
    external: true
