services:
  main-site:
    build: .
    container_name: main-site
    restart: unless-stopped
    # main-site 无本地数据库，不需要挂载 public 目录
    networks:
      webnet:
        aliases:
          - main-site

networks:
  webnet:
    external: true
